In [11]:
import nfl_data_py as nfl

In [12]:
df_weekly = nfl.import_weekly_data(years=[2022])

Downcasting floats.

In [13]:
df_weekly.head()

,player_id,player_name,player_display_name,position,position_group,headshot_url,recent_team,season,week,season_type,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,TB,2022,1,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,10.38,10.38
1,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,TB,2022,2,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,9.40,9.40
2,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,TB,2022,3,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,14.74,14.74
3,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,TB,2022,4,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,25.40,25.40
4,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,TB,2022,5,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,19.74,19.74

In [14]:
df_weekly.shape

(5631, 53)

In [15]:
df_weekly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5631 entries, 0 to 5630
Data columns (total 53 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    5631 non-null   object
 1   player_name                  5631 non-null   object
 2   player_display_name          5631 non-null   object
 3   position                     5631 non-null   object
 4   position_group               5631 non-null   object
 5   headshot_url                 5631 non-null   object
 6   recent_team                  5631 non-null   object
 7   season                       5631 non-null   int32
 8   week                         5631 non-null   int32
 9   season_type                  5631 non-null   object
 10  opponent_team                5631 non-null   object
 11  completions                  5631 non-null   int32
 12  attempts                     5631 non-null   int32
 13  passing_yards                5631 non-null   float32
 14  passing_tds                  5631 non-null   int32
 15  interceptions                5631 non-null   float32
 16  sacks                        5631 non-null   float32
 17  sack_yards                   5631 non-null   float32
 18  sack_fumbles                 5631 non-null   int32
 19  sack_fumbles_lost            5631 non-null   int32
 20  passing_air_yards            5631 non-null   float32
 21  passing_yards_after_catch    5631 non-null   float32
 22  passing_first_downs          5631 non-null   float32
 23  passing_epa                  693 non-null    float32
 24  passing_2pt_conversions      5631 non-null   int32
 25  pacr                         685 non-null    float32
 26  dakota                       607 non-null    float32
 27  carries                      5631 non-null   int32
 28  rushing_yards                5631 non-null   float32
 29  rushing_tds                  5631 non-null   int32
 30  rushing_fumbles              5631 non-null   float32
 31  rushing_fumbles_lost         5631 non-null   float32
 32  rushing_first_downs          5631 non-null   float32
 33  rushing_epa                  2386 non-null   float32
 34  rushing_2pt_conversions      5631 non-null   int32
 35  receptions                   5631 non-null   int32
 36  targets                      5631 non-null   int32
 37  receiving_yards              5631 non-null   float32
 38  receiving_tds                5631 non-null   int32
 39  receiving_fumbles            5631 non-null   float32
 40  receiving_fumbles_lost       5631 non-null   float32
 41  receiving_air_yards          5631 non-null   float32
 42  receiving_yards_after_catch  5631 non-null   float32
 43  receiving_first_downs        5631 non-null   float32
 44  receiving_epa                4547 non-null   float32
 45  receiving_2pt_conversions    5631 non-null   int32
 46  racr                         4521 non-null   float32
 47  target_share                 4547 non-null   float32
 48  air_yards_share              4547 non-null   float32
 49  wopr                         4547 non-null   float32
 50  special_teams_tds            5631 non-null   float32
 51  fantasy_points               5631 non-null   float32
 52  fantasy_points_ppr           5631 non-null   float32
dtypes: float32(29), int32(15), object(9)
memory usage: 1.3+ MB

In [16]:
df_weekly.isnull().sum()

player_id                         0
player_name                       0
player_display_name               0
position                          0
position_group                    0
headshot_url                      0
recent_team                       0
season                            0
week                              0
season_type                       0
opponent_team                     0
completions                       0
attempts                          0
passing_yards                     0
passing_tds                       0
interceptions                     0
sacks                             0
sack_yards                        0
sack_fumbles                      0
sack_fumbles_lost                 0
passing_air_yards                 0
passing_yards_after_catch         0
passing_first_downs               0
passing_epa                    4938
passing_2pt_conversions           0
pacr                           4946
dakota                         5024
carries                           0
rushing_yards                     0
rushing_tds                       0
rushing_fumbles                   0
rushing_fumbles_lost              0
rushing_first_downs               0
rushing_epa                    3245
rushing_2pt_conversions           0
receptions                        0
targets                           0
receiving_yards                   0
receiving_tds                     0
receiving_fumbles                 0
receiving_fumbles_lost            0
receiving_air_yards               0
receiving_yards_after_catch       0
receiving_first_downs             0
receiving_epa                  1084
receiving_2pt_conversions         0
racr                           1110
target_share                   1084
air_yards_share                1084
wopr                           1084
special_teams_tds                 0
fantasy_points                    0
fantasy_points_ppr                0
dtype: int64

In [17]:
df_weekly.describe()

,season,week,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,sack_fumbles,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
count,5631.0,5631.000000,5631.000000,5631.000000,5631.000000,5631.000000,5631.000000,5631.000000,5631.000000,5631.000000,...,5631.000000,4547.000000,5631.000000,4521.000000,4547.000000,4547.000000,4547.000000,5631.000000,5631.000000,5631.000000
mean,2022.0,9.937666,2.166400,3.375244,23.684425,0.141005,0.077429,0.240810,1.586752,0.032499,...,1.139052,0.639631,0.007636,0.882009,0.124918,0.124918,0.274819,0.002486,6.302057,8.468456
std,0.0,5.588639,6.637119,10.235175,73.065651,0.537748,0.357175,0.887996,6.019763,0.208629,...,1.510539,3.190765,0.087059,4.687256,0.091267,0.154357,0.227671,0.053252,6.859687,7.851121
min,2022.0,1.000000,0.000000,0.000000,-3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-12.414369,0.000000,-49.000000,0.016129,-0.842105,-0.078195,0.000000,-3.040000,-3.040000
25%,2022.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-0.981148,0.000000,0.000000,0.050000,0.010741,0.094909,0.000000,1.100000,2.100000
50%,2022.0,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.309670,0.000000,0.767857,0.100000,0.070652,0.200546,0.000000,3.800000,6.300000
75%,2022.0,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,2.142391,0.000000,1.358974,0.178571,0.206687,0.402247,0.000000,9.700000,12.900000
max,2022.0,22.000000,43.000000,68.000000,481.000000,6.000000,4.000000,9.000000,61.000000,3.000000,...,10.000000,16.174366,1.000000,96.000000,0.531250,1.842105,1.789474,2.000000,51.099998,55.099998

In [18]:
df_weekly.value_counts()

player_id   player_name  player_display_name  position  position_group  headshot_url                                                                        recent_team  season  week  season_type  opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr      dakota     carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr      special_teams_tds  fantasy_points  fantasy_points_ppr
00-0019596  T.Brady      Tom Brady            QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/q7dpdlxyu5rs05rgh1le  TB           2022    10    REG          SEA            22           29        258.0          2            1.0            0.0    -0.0        0             0                  248.0              92.0                       15.0                  15.308453   0                        1.040323   0.282559  6        -3.0           0            0.0              0.0                   0.0                  -2.944238    0                        0           1         0.0             0              0.0                0.0                      16.0                0.0                          0.0                    -4.726017      0                          0.0   0.034483       0.061303        0.094636  0.0                16.020000       16.020000             1
00-0029263  R.Wilson     Russell Wilson       QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/gebzv2aljujgleboe4ns  DEN          2022    4     REG          LV             17           25        237.0          2            0.0            3.0     23.0       0             0                  284.0              70.0                       7.0                  -1.025830    0                        0.834507   0.032958  4         29.0          1            0.0              0.0                   2.0                   2.353157    0                        1           1         1.0             0              0.0                0.0                     -1.0                 2.0                          0.0                    -0.384638      0                          0.0   0.040000      -0.003521        0.057535  0.0                26.480000       27.480000             1
00-0029604  K.Cousins    Kirk Cousins         QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/viuxnyezrwdfjnxsfssb  MIN          2022    19    POST         NYG            31           39        273.0          2            0.0            0.0    -0.0        0             0                  268.0              127.0                      16.0                  12.248064   0                        1.018657   0.242834  1         1.0           1            0.0              0.0                   1.0                   0.622661    0                        1           1        -2.0             0              0.0                0.0                     -6.0                 4.0                          0.0                    -2.380199      0                          0.0   0.025641      -0.024291        0.021457  0.0                24.820000       25.820000             1
00-0033106  J.Goff       Jared Goff           QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/nyitt4ybuzopzjzddafi  DET          2022    8     REG          MIA            27           37        321.0          1            0.0            1.0     10.0       0             0                  267.0              178.0                      13.0                  8.690999    0                        1.202247   0.138565  1         3.0           0            0.0              0.0                   0.0                  -0.370586    0                        1           1         5.0             0              0.0                0.0                     -4.0                 9.0                          0.0                    -0.100160      0                          0.0   0.027027      -0.014981        0.030054  0.0                17.639999       18.639999             1
00-0033873  P.Mahomes    Patrick Mahomes      QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/oagzjdsdoezmp6frggrn  KC           2022    17    REG          DEN            29           42        328.0          3            1.0            0.0    -0.0        0             0                  313.0              187.0                      18.0                  10.644172   0                        1.047923   0.148474  4         8.0           0            0.0              0.0                   0.0                  -4.825059    0                        1           1         6.0             0              0.0                0.0                     -9.0                 15.0                         0.0                     0.351021      0                          0.0   0.024390      -0.029032        0.016263  0.0                24.520000       25.520000             1
00-0036355  J.Herbert    Justin Herbert       QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/fwjdvww4dv36k8tvsws6  LAC          2022    7     REG          SEA            33           51        293.0          2            1.0            3.0     17.0       1             1                  321.0              193.0                      17.0                 -10.389351   0                        0.912773  -0.001437  3         22.0          0            0.0              0.0                   1.0                   1.234362    0                        1           1        -8.0             0              0.0                0.0                     -8.0                 0.0                          0.0                    -1.788918      0                          0.0   0.019608      -0.024922        0.011966  0.0                17.120001       18.120001             1
                                                                                                                                                                                 11    REG          KC             23           30        280.0          2            1.0            5.0     30.0       0             0                  243.0              111.0                      12.0                  6.737907    0                        1.152263   0.204093  5         17.0          0            0.0              0.0                   3.0                   3.955465    0                        1           1        -2.0             0              0.0                0.0                     -7.0                 5.0                          0.0                    -0.998840      0                          0.0   0.034483      -0.030568        0.030327  0.0                18.700001       19.700001             1
00-0037013  Z.Wilson     Zach Wilson          QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/xkio4hljxo2u59rk2bud  NYJ          2022    4     REG          PIT            18           36        252.0          1            2.0            1.0     4.0        0             0                  331.0              97.0                       11.0                  1.162869    0                        0.761329   0.017160  2         15.0          0            0.0              0.0                   0.0                  -0.300908    0                        1           1         2.0             1              0.0                0.0                      2.0                 0.0                          1.0                     1.184453      0                          1.0   0.030303       0.006757        0.050184  0.0                17.780001       18.780001             1
00-0038108  B.Zappe      Bailey Zappe         QB        QB              https://static.www.nfl.com/image/private/f_auto,q_auto/league/qr1opoisbs0vmu2pm8rz  NE           2022    6     REG          CLE            24           34        309.0          2            0.0            2.0     8.0        1             1                  172.0              165.0                      14.0                  8.408839    0                        1.796512   0.216459  3        -4.0           0            0.0              0.0                   0.0                   0.000000    0                        1           1        -6.0             0              0.0                0.0                     -8.0                 2.0                          0.0                    -1.242592      0                          0.0   0.032258      -0.043716        0.017786  0.0                17.360001       18.360001             1
dtype: int64

In [19]:
df_qb = df_weekly[df_weekly['position'] == 'QB']
df_wr = df_weekly[df_weekly['position'] == 'WR']

In [20]:
df_qb = df_qb.drop(columns=['player_display_name', 'season_type', 'headshot_url'])

In [38]:
df_qb.describe()

,season,week,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,sack_fumbles,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
count,677.0,677.000000,677.000000,677.000000,677.000000,677.000000,677.000000,677.000000,677.000000,677.000000,...,677.000000,19.000000,677.0,18.000000,19.000000,19.000000,19.000000,677.0,677.000000,677.000000
mean,2022.0,10.146233,17.994092,28.029542,196.757751,1.166913,0.638109,1.992615,13.116692,0.267356,...,0.008863,-0.399850,0.0,0.342144,0.039598,0.013642,0.068947,0.0,13.794536,13.821123
std,0.0,5.610710,9.037559,13.435217,101.779861,1.097428,0.835897,1.750301,12.235835,0.544755,...,0.093793,1.568506,0.0,0.533670,0.020623,0.067672,0.076184,0.0,8.824731,8.825583
min,2022.0,1.000000,0.000000,0.000000,-3.000000,0.000000,0.000000,0.000000,-0.000000,0.000000,...,0.000000,-4.726017,0.0,0.000000,0.019608,-0.043716,0.011966,0.0,-3.040000,-3.040000
25%,2022.0,5.000000,13.000000,21.000000,139.000000,0.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,-1.142853,0.0,0.000000,0.028665,-0.019636,0.028493,0.0,7.540000,7.560000
50%,2022.0,10.000000,19.000000,30.000000,210.000000,1.000000,0.000000,2.000000,11.000000,0.000000,...,0.000000,-0.273275,0.0,0.000000,0.034483,-0.003521,0.051064,0.0,13.680000,13.680000
75%,2022.0,15.000000,24.000000,37.000000,264.000000,2.000000,1.000000,3.000000,20.000000,0.000000,...,0.000000,0.847067,0.0,0.684091,0.040000,0.014612,0.068234,0.0,19.020000,19.059999
max,2022.0,22.000000,43.000000,68.000000,481.000000,6.000000,4.000000,9.000000,61.000000,3.000000,...,1.000000,1.826417,0.0,1.600000,0.107143,0.266990,0.347607,0.0,42.720001,42.720001

In [23]:
df_wr.info()
columns_all_player = ['player_id', 'player_name', 'position', 'recent_team', 'season', '']
wr_columns = []

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2238 entries, 59 to 5630
Data columns (total 53 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    2238 non-null   object
 1   player_name                  2238 non-null   object
 2   player_display_name          2238 non-null   object
 3   position                     2238 non-null   object
 4   position_group               2238 non-null   object
 5   headshot_url                 2238 non-null   object
 6   recent_team                  2238 non-null   object
 7   season                       2238 non-null   int32
 8   week                         2238 non-null   int32
 9   season_type                  2238 non-null   object
 10  opponent_team                2238 non-null   object
 11  completions                  2238 non-null   int32
 12  attempts                     2238 non-null   int32
 13  passing_yards                2238 non-null   float32
 14  passing_tds                  2238 non-null   int32
 15  interceptions                2238 non-null   float32
 16  sacks                        2238 non-null   float32
 17  sack_yards                   2238 non-null   float32
 18  sack_fumbles                 2238 non-null   int32
 19  sack_fumbles_lost            2238 non-null   int32
 20  passing_air_yards            2238 non-null   float32
 21  passing_yards_after_catch    2238 non-null   float32
 22  passing_first_downs          2238 non-null   float32
 23  passing_epa                  17 non-null     float32
 24  passing_2pt_conversions      2238 non-null   int32
 25  pacr                         13 non-null     float32
 26  dakota                       0 non-null      float32
 27  carries                      2238 non-null   int32
 28  rushing_yards                2238 non-null   float32
 29  rushing_tds                  2238 non-null   int32
 30  rushing_fumbles              2238 non-null   float32
 31  rushing_fumbles_lost         2238 non-null   float32
 32  rushing_first_downs          2238 non-null   float32
 33  rushing_epa                  349 non-null    float32
 34  rushing_2pt_conversions      2238 non-null   int32
 35  receptions                   2238 non-null   int32
 36  targets                      2238 non-null   int32
 37  receiving_yards              2238 non-null   float32
 38  receiving_tds                2238 non-null   int32
 39  receiving_fumbles            2238 non-null   float32
 40  receiving_fumbles_lost       2238 non-null   float32
 41  receiving_air_yards          2238 non-null   float32
 42  receiving_yards_after_catch  2238 non-null   float32
 43  receiving_first_downs        2238 non-null   float32
 44  receiving_epa                2204 non-null   float32
 45  receiving_2pt_conversions    2238 non-null   int32
 46  racr                         2197 non-null   float32
 47  target_share                 2204 non-null   float32
 48  air_yards_share              2204 non-null   float32
 49  wopr                         2204 non-null   float32
 50  special_teams_tds            2238 non-null   float32
 51  fantasy_points               2238 non-null   float32
 52  fantasy_points_ppr           2238 non-null   float32
dtypes: float32(29), int32(15), object(9)
memory usage: 559.5+ KB

In [25]:
df_seasonal = nfl.import_seasonal_data([2022])

In [27]:
df_seasonal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 619 entries, 0 to 618
Data columns (total 58 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    619 non-null    object
 1   season                       619 non-null    int64
 2   season_type                  619 non-null    object
 3   completions                  619 non-null    int32
 4   attempts                     619 non-null    int32
 5   passing_yards                619 non-null    float64
 6   passing_tds                  619 non-null    int32
 7   interceptions                619 non-null    float64
 8   sacks                        619 non-null    float64
 9   sack_yards                   619 non-null    float64
 10  sack_fumbles                 619 non-null    int32
 11  sack_fumbles_lost            619 non-null    int32
 12  passing_air_yards            619 non-null    float64
 13  passing_yards_after_catch    619 non-null    float64
 14  passing_first_downs          619 non-null    float64
 15  passing_epa                  619 non-null    float64
 16  passing_2pt_conversions      619 non-null    int32
 17  pacr                         619 non-null    float64
 18  dakota                       619 non-null    float64
 19  carries                      619 non-null    int32
 20  rushing_yards                619 non-null    float64
 21  rushing_tds                  619 non-null    int32
 22  rushing_fumbles              619 non-null    float64
 23  rushing_fumbles_lost         619 non-null    float64
 24  rushing_first_downs          619 non-null    float64
 25  rushing_epa                  619 non-null    float64
 26  rushing_2pt_conversions      619 non-null    int32
 27  receptions                   619 non-null    int32
 28  targets                      619 non-null    int32
 29  receiving_yards              619 non-null    float64
 30  receiving_tds                619 non-null    int32
 31  receiving_fumbles            619 non-null    float64
 32  receiving_fumbles_lost       619 non-null    float64
 33  receiving_air_yards          619 non-null    float64
 34  receiving_yards_after_catch  619 non-null    float64
 35  receiving_first_downs        619 non-null    float64
 36  receiving_epa                619 non-null    float64
 37  receiving_2pt_conversions    619 non-null    int32
 38  racr                         619 non-null    float64
 39  target_share                 619 non-null    float64
 40  air_yards_share              619 non-null    float64
 41  wopr_x                       619 non-null    float64
 42  special_teams_tds            619 non-null    float64
 43  fantasy_points               619 non-null    float64
 44  fantasy_points_ppr           619 non-null    float64
 45  games                        619 non-null    int64
 46  tgt_sh                       619 non-null    float64
 47  ay_sh                        619 non-null    float64
 48  yac_sh                       619 non-null    float64
 49  wopr_y                       619 non-null    float64
 50  ry_sh                        619 non-null    float64
 51  rtd_sh                       598 non-null    float64
 52  rfd_sh                       619 non-null    float64
 53  rtdfd_sh                     619 non-null    float64
 54  dom                          598 non-null    float64
 55  w8dom                        598 non-null    float64
 56  yptmpa                       619 non-null    float64
 57  ppr_sh                       619 non-null    float64
dtypes: float64(41), int32(13), int64(2), object(2)
memory usage: 253.9+ KB